services:
  - type: web
    name: amit-das
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JARVIS_ADMIN_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
